### ISSUE TITLE
Song View

### ISSUE THREAD

**Issue by chronoDave** [chronoDave/Doombox#64]
Requirements
 - [ ] List of songs displaying user-defined values, defaults to: `title`, `artist`, `album`, `label` and `duration`.
 - [ ] List must be scalable (preferably with a horizontal scrollbar)
 - [ ] List must be groupable, defaults to `album`
 - [ ] All songs must be able to be added to the playlist at once (both sequential and shuffled)
 - [ ] Grouped songs must be able to be added to the playlist at once (both sequential and shuffled)
 - [ ] Single songs must be able to be played <b>without</b> being added to the playlist. The playlist should continue after the song finished
 - [ ] Single songs must be able to be added to the playlist
 - [ ] Column sizes must be adjustable, defaults to an even split
 - [ ] All user-defined features should be persistent (column size, group, column types)
