### ISSUE TITLE
Album / Label View

### ISSUE THREAD

**Issue by chronoDave** [chronoDave/Doombox#65]
- [ ] Classic Album / Label View must be merged into Album View.
 - [ ] Albums must be able to be grouped, defaults to `label`
 - [ ] Albums must be able to be added to the playlist (both sequential and shuffled)
 - [ ] All albums must be able to be added to the playlist (both sequential and shuffled)
 - [ ] All grouped albums must be able to be added to the playlist (both sequential and shuffled)
 - [ ] An album must display it's songs when selected (preferable in a new window of sorts)
