### ISSUE TITLE
Menu Bar / Tab

### ISSUE THREAD

**Issue by chronoDave** [chronoDave/Doombox#66]
Menu bar / tab are both in the same module `Menu`.
- [x] Menu bar should contain the following items: `Logo`, `Master playlist`, `Album view`, `Song view` and `Custom playlists`.
- [x] Right-clicking on these items should display a context menu.
- [x] Playlists are stored in a new datastore, `playlist`.
- [x] Every playlist must contain: `_id`, `title`, `image`, `songs`.
- [x] Songs contains a list of id's, which gets populated when the playlist is retrieved.
- [x] There must be an indicator indicating which route / view is active.
- [x] The menu tab displays the following items: `Player`, `Header`, `Playlist`
